var arr =["“No one is perfect,thats why pencils have erasers.-Wolfgang Riebe”.",
"Once you replace negative thoughts with positive ones, you’ll start having positive results-Willie Nelson.",
"“Happiness is the only thing that multiplies when you share it.-Albert Schweitzer”",
"“The struggle you’re in today is developing the strength you need tomorrow.-Robert Tew”",
"“Winning doesn’t always mean being first. Winning means you’re doing better than you’ve done before.-Bonnie Blair”",
"“Live life to the fullest and focus on the positive.-Matt Cameron”",
"“Wherever you go, no matter what the weather, always bring your own sunshine.”-Anthony J. D’Angelo",
"“Love yourself first and everything else falls into line. You really have to love yourself to get anything done in this world.”-Lucille Ball",
"“Hearts will never be practical until they are made unbreakable.”-The Wizard of Oz",
"“Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.”- Martin Luther King Jr.",
"“Life is a journey,not a destination.-Ralph waldo Emerson”",
"“Attitude is a littel thing that makes a big difference-unknown author”",
"“A Room without books ia like a body without a soul.-Marcus Tullius cicero ”",
"“Make each day your masterpiece -John Wooden”",
"“Life is 10% what happens to us and 90% how we react to it-Dennis P.Kimbro”",
"“I never dreamed about succes i worked for it.-Estee lauder”",
"“ Good friends are hard to find,harder to leave and impossible to forget.-G.Randolf”",
"“True friends never leave you during hard times-unknown auther”",
"“To be brave is to love unconditionally without expecting anything in return.”– Madonna",
"“effort are better than promises-unknown author”",
"“Each song hase one line always falll in love with-##”",
"“Your life is your message-Gandhi  ”",
"“The grastest science in the world in heaven and on earth-Mother Teresa”",
"“ Not all od us can do greate things but we can do small things with great love.-Mother Teresa.”",
"“Sometimes,its better to bunk a class and enjoy with friends,becauase now, when I look back,mark never make me laugh,but memories do.-APJ Abdul Kalam. ”",
"“Life most memorable days are the school days..-unknown ”",
"“ We do not remember days we remember moments-Cesare pavese”",
"“Two memorable days of my life,The day we met The day you left-someone write.”",
"“ That day wsa the most memorable day for me when i met you.....-Ayushi”",
"“Die with your memorie, not a Dream-Tiny Buddha.”",
"“Spread love everywhere yo go let no one ever come to you without leaving happier-Mother Teresa. ”",
"“The two most powerful warriors are patience and time.-Leo Tolstoy","Those who are free of resentful thoughts surely find peace.-Buddha”",
"“Talk doesn't cook rice.-Chinese proverb“",
"“A short saying often contains much wisdom.-Sophocles “",
"“Life is movement-we breathe, we eat, we walk, we move!-John Pierrakos“",
"“Only do what your heart tells you.-Princess Diana “",
"“Never mistake activity for achievement.-John Wooden “",
"“What worries you masters you-Haddon Robinson “",
"“One faces the future with ones past-Pearl Buck“",
"“Who sows virtue reaps honour-Leonardo da Vinci.“",
"“Be kind whenever possible. It is always possible.-Dalai Lama“",
"“ Talk doesn't cook rice.-Chinese proverb“",
"“Be as you wish to seem-Socrate “",            
"“A goal without a plan is just a wish.-Larry Elder“",
"“To succeed, we must first believe that we can.-Michael Korda “",
"“ Do, or do not. There is no try-Yoda“",
"“All serious daring starts from within.-Harriet Beecher Stowe “",
"“The best teacher is experience learned from failures-Byron Pulsifer “",
"“Think how hard physics would be if particles could think. -Murray Gell-Mann“",
"“Love is the flower you've got to let grow.-John Lennon “",
"“ Don't wait. The time will never be just right.-Napoleon Hil“",
"“One fails forward toward success-Charles Kettering “",
"“ This is a new year. A new beginning. And things will change.-Taylor Swift“",
"“School bells are ringing loud and clear; vacation’s over, school is here.-Winifred C. Marshal “",
"“Today is the first day of the rest of your life.-Charles Dederich“",
"“The most important day of a person’s education is the first day of school, not Graduation Day-Harry Wong “",
"“A short saying often contains much wisdom. “",
"“The day is already blessed, find peace within it. “",
"“ It takes both sunshine and rain to make a rainbow“",
"“A beautiful thing is never perfect. “",
"“ Only do what your heart tells you.-Princess Diana“",
"“Life is movement-we breathe, we eat, we walk, we move!-John Pierrakos “",
"“Important principles may, and must, be inflexible-Abraham Lincoln“",
"“ Our distrust is very expensive.-Ralph Emerson“",
"“Change in all things is sweet-Aristotle “",
]
var RandomQuote=document.getElementById('quotesdiplay'); 
function newQuote(){
    RandomQuote.style.display="block";
    var Number = Math.floor( Math.random() * (38 - 0 + 1) ) + 0;  
    var quotes = arr[Number];
    RandomQuote.innerText= quotes; 
    console.log(quotes);
}
newQuote()
